version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/cert:/etc/nginx/cert:ro
      - ./docker/nginx/pwd/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - common

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    platform: linux/amd64
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - common

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_php
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - common
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    environment:
      APP_ENV: "local"

  socket:
    build:
      context: .
      dockerfile: docker/socket/Dockerfile
    container_name: laravel_socket
    ports:
      - "2277:8443"
    environment:
      - NODE_ENV=local
      - REDIS_HOST=redis
    volumes:
      - ./:/app
    networks:
      - common
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - common

volumes:
  mysql:
  redis_data:

networks:
  common:
    driver: bridge